### ISSUE TITLE
Transaction is vague

### ISSUE THREAD

**Issue by rhiaro** [alephdata/followthemoney#10]
Improve how Transactions are modelled. Figure out better terms than `to` and `from` for the involved parties. Maybe flatten it altogether. Discuss?

Transaction kind of things include:
* Payments
* Property
* Debts/mortgages
* Economic activity
* Human communication?
* ...

**Comment by pudo** [comment]
I think there are similarities between a Payment, EcAct and Communication, i.e. the `sender`, `receiver` aspect.

**Comment by pudo** [comment]
Thinking from the UI end: it doesn't make sense to me to have two tabs in the entity display, one for transactions received and one for transactions originated, which would then mix together bank payments customs declarations, and emails. Perhaps it makes sense to treat them entirely differently?

**Comment by rhiaro** [comment]
Would they not be grouped by the subtype of Transaction in the UI?

**Comment by pudo** [comment]
No it's grouped by the qname of the property, i.e. Transaction:from, Transaction:to

**Comment by pudo** [comment]
@uhhhuh merged :)
