### ISSUE TITLE
class doc links are broken on Schema Extension page

### ISSUE THREAD

**Issue by jbothma** [alephdata/followthemoney#1171]
These two class links https://github.com/alephdata/followthemoney/blob/a77f7fea095a98e7cd6137454e3ea962ebdaf3c4/docs/src/pages/docs/custom.mdx#L27 are broken because they get a trailing slash, e.g. https://followthemoney.tech/reference/python/followthemoney/schema.html/#Schema

I'm not sure how to fix it quickly

**Comment by tillprochaska** [comment]
Thanks @jbothma for paying attention :) Didn’t notice this as the local dev server did resolve the page properly even with the trailing slash… Should be fixed now :)

**Comment by jbothma** [comment]
Thanks! :)
