### ISSUE TITLE
nitpick: write_entity should close the file handler

### ISSUE THREAD

**Issue by catileptic** [alephdata/followthemoney#1418]
the [write_entity method](https://github.com/alephdata/followthemoney/blob/main/followthemoney/cli/util.py#L30) should perform `fh.close()` before returning.

this is such a small nitpick that it would be great for it to be included in some future FTM release, alongside more important work

**Comment by pudo** [comment]
`write_entity` gets called in the inner loop of data exports, i.e. it's called for each entity to generate newline-delimited files. Closing it in this method would abort such exports.

**Comment by catileptic** [comment]
@pudo fair point! i guess i was near-sighted when i opened this, coming from some work on ftm store. thanks for your input, closing this issue.
