### ISSUE TITLE
OpenOwnership enricher

### ISSUE THREAD

**Issue by augusto-herrmann** [alephdata/followthemoney#172]
A process for enriching a followthemoney entity and its relationships by looking it up in the [OpenOwnership Register](https://register.openownership.org/). From their website:

> ## Freely licensed data, in bulk
> 
> We release all of our data as an open ledger, formatted using the Beneficial Ownership Data Standard (BODS).
> 
> This data is updated monthly, and made available as a free download under the Open Data Commons Attribution License.
> 
> Currently containing nearly 20 million BODS statements, in a 10GB JSONLines file.

Navigating the maze of corporate shell companies that own one another is a big challenge for investigative reporting and money laundering investigations. Beneficial ownership data seems to be especially useful for following the money on a project like aleph.

**Comment by pudo** [comment]
Hey @augusto-herrmann, long time no see. I'd love to see a PR that could convert OpenOwnership data to Follow The Money entities, it'd be super useful to have as more jurisdictions of OO data go online (so far it's been a pretty limited set, and the OO web site mixes up all the sources which makes much harder to use in practice). 

The way this could be implemented could be analogous to the OCDS importer we have. This is simply a command-line option like this: 

```bash
cat opentender.eu.json | ftm import-ocds | ftm aggregate >opentender.ftm.json
```

The [code for this](https://github.com/alephdata/followthemoney/blob/master/followthemoney/cli/ocds.py) is quite simple.

**Comment by pudo** [comment]
This is WIP here now: https://github.com/opensanctions/bods-ftm

**Comment by pudo** [comment]
I don't think there's actually an open action on this, closing as done.

**Comment by augusto-herrmann** [comment]
Cool! Good job, @pudo.
