### ISSUE TITLE
Generic MISP to Aleph exporter

### ISSUE THREAD

**Issue by Rafiot** [alephdata/followthemoney#247]
This is a long shot question: I want to export MISP data to aleph. We have any possible type of information in MISP, and the generic representation is the following:
* Event
  * contains standalone attributes and objects 
  * has metadata (tags, date, comment)
* Object
  * contains attributes
  * Has a comment, will have tags
* Attribute
  * value of a certain type
  * tags

In a lucky case, the object(s) are the 1:1 mapping to FTM schema, so we can directly export them.

In all the other cases, we have anything possible, from a file object representing a malware sample to the description of an attack against the ss7 infrastructure. Mapping each individual MISP Object to a dedicated FTM schema would be an awful mess, and anyone needing that granularity should just use MISP.

The use case I have in mind is using aleph as a organized container for data coming from not very structured sources, but have correlation with the structured information I have in a MISP instance.

Would it make sense to just consider each individual objects as documents, with the event itself as a parent?

**Comment by pudo** [comment]
I'm curious if there's still an active use case for this?

**Comment by Rafiot** [comment]
I didn't really manage to allocate time to it, and will probably not in the close future. Closing it for now, and I'll hopefully be able to play with Aleph again at some point. Sorry for that.
