### ISSUE TITLE
TaxRoll Schema appears to have gotten some breaking changes

### ISSUE THREAD

**Issue by Ueland** [alephdata/followthemoney#28]
Usage of it only throws this when creating a new object via the API:
```{"status": "error", "errors": "Unknown property (<Schema('TaxRoll')>): name"}```

For some reason, it does not end up in the API console.

Will work-around it for now by declaring a Thing, might look into this issue later if nobody beats me too it.

**Comment by Ueland** [comment]
I will get it done, gives me a chance to play a bit more with the code :)

**Comment by Ueland** [comment]
Created PR #29 which i suspect should be a bit more correct, based on our discussion.

**Comment by pudo** [comment]
Closing after PR is merged.
