### ISSUE TITLE
URLs miss the fragment after '#'

### ISSUE THREAD

**Issue by uhhhuh** [alephdata/followthemoney#280]
urlnormalizer.normalize_url returns urls with the part that follows "#" dropped.
"https://a.b.c/index.jsp#/ROC/companyDetailsRO.do?action=companyDetails&companyId=123" becomes "https://a.b.c/index.jsp"

**Comment by simonwoerpel** [comment]
I am not sure if it is a bug or there are reasons why it is implemented with dropping the fragments, but i opened a PR that could solve this issue: https://github.com/alephdata/followthemoney/pull/282

**Comment by pudo** [comment]
Adopted, closing.
