### ISSUE TITLE
Introduce Address schema

### ISSUE THREAD

**Issue by pudo** [alephdata/followthemoney#38]
I think it's time we introduced an `Address` object with a link from `Thing`. What fields do we need? 

* `co`
* `street`
* `apartment`
* `city`, `town`, `settlement`
* `postalCode`
* `region`
* `country`
* `text` (for when it's just a long string).

How can we then have a special function that keys it into a single string?

**Comment by tendai-zw** [comment]
possibly match it with open street maps nomatim address
      * Country 
      * City
      * Area
      * CountryCode
      * State 
      * Locality
      * Postcode
      * Building instead of Apartment

**Comment by sunu** [comment]
`latitude` and `longitude` are worth including as well if we aim to do GIS and maps in the future

**Comment by pnnlAlan** [comment]
Tracking a changing address or location over time is often very important. It would be useful to make this "Location" extend Interval.

**Comment by pudo** [comment]
In terms of generating a label from components, here are some tools and a template set (thanks to @kimryan!)

https://metacpan.org/pod/Geo::Address::Formatter
https://github.com/OpenCageData/address-formatting/blob/master/conf/components.yaml
