### ISSUE TITLE
Crew Lists for Vessels (Multiple Names)

### ISSUE THREAD

**Issue by StoltHD** [alephdata/followthemoney#388]
Would it be possible for you to add a property field for Crew on the Vessel Entity?

I'm working with finding some people in historical Crew Lists and it would have been great if there was a Field where I in an easy way could add Names of  all the Crew Members (and Occupations and Age if possible) instead of have to create one Entity for each and every one (can be 20-50 for each ship).

And if those Names was automatically linked to a Person Entity (Node) if it existed in the Graph, same way as Places and Dates are...

**Comment by pudo** [comment]
Could be a `Crew` interval linking a person and a vessel?

**Comment by StoltHD** [comment]
Problem with that is that I suddenly could get 1500-2000 people in the graph, I can already link with a Custom Link and just name it, but I was hoping for a list of people that automatically linked when I added people in that list as a Person Node.

Or if there was a Document Node where it was possible to add a few Entities of list type of "participants", then I could add that document to the ships as a Crew List, if the Property Fields also could be named, that would give the possibility to create one document with different types of participants... i.e. Signed On, Sign Off, Discards, Injured, etc. 

Something similar to the "Involved" field in Events.

The best way would actually be if it was possible to have a Document Node Type where that "Involved" field could be added.

That way a Crew list could be linked either to an Event "journey of the ship" or directly to the ship with a Custom link type "crew list".

A document type like that would also be possible to use as any type of member list.  and it could also be used as a "Source Document", not that I ever have figured out how to use that Entity Field.

There is actually a way to few Document Types in Aleph Desktop, and the few that is, are way to limited regarding fields, so I am finding my self going back to i.e. Cytoscape over and over again, even though I like your software...

Digression: It should also have been possible to import/export graphML or other open standard network graph format directly from the desktop app... (not everyone want to use cloud storage for their research.

**Comment by pudo** [comment]
For the record: I don't understand this issue at all, and would propose to close it for inactivity. Not sure we've seen the need to express "crew" multiple times.
