### ISSUE TITLE
Add a `misc` property to store the left-over data

### ISSUE THREAD

**Issue by uhhhuh** [alephdata/followthemoney#42]
To keep the `non-mapped` bits of data and store that in a json format.

**Comment by pudo** [comment]
We already have a mechanism that can handle this in `followthemoney` core. Basically, if the library is passed a JSON structure that contains keys other than `schema`, `id`, `properties`, then these are placed in the `context` variable on the `EntityProxy`. What does not exist is a way to use a mapping to copy data into `context`. So we could just add a new section to the mapping syntax for an entity which allows a user to specify `context` fields that should be copied in.

**Comment by pudo** [comment]
Ok, I'm closing this as it seems we have the described functionality?
