### ISSUE TITLE
Thing's name properties are just strings

### ISSUE THREAD

**Issue by mynameisfiber** [alephdata/followthemoney#526]
It seems to me that a Thing's `name` property should be of `name` type and not `string` type. This way thing's names would be matchable by the various comparison operations.

Thoughts?

**Comment by brrttwrks** [comment]
I agree. Was trying to xref a dataset that had vessels and legal entities in it - only legal entity matches were returned. The outcome felt inconsistent, and a full search of Aleph returned vessels in other datasets with similar names and IDs. Seems like the names should be matchable. Would that cause any problems elsewhere?

**Comment by mynameisfiber** [comment]
Poking around a bit more, it seems that a `Thing`'s other name-like properties ("Other name", "Other name") are correctly of type `name`. I think this is a bug and not a clever choice.

**Comment by mynameisfiber** [comment]
> Would that cause any problems elsewhere?

@brrttwrks I don't think so. I'll give other people some time to comment before making the change though.
