### ISSUE TITLE
Define which properties should be used to display an entity in a timeline

### ISSUE THREAD

**Issue by tillprochaska** [alephdata/followthemoney#811]
I’m currently thinking about enhancements for the timelines feature in Aleph. One common user request is to actually visualize timeline items. For example like this:

![timelines example](https://user-images.githubusercontent.com/1512805/188194957-f7bb6823-5dc7-4a84-9e37-c84fd407596b.png)

Every entity would be represented by a bar. The position and length of the bar depends on the start and end date of the entity. Which properties should be considered the start/end date of an entity can be different per entity.

It’s fairly simple for interval entities -- as they all have `date`/`startDate` and `endDate` properties. It’s not that simple in other cases, and there might be even multiple properties that could be used as an entites start/end date.

| Schema | start date | end date |
| - | - | - |
| `LegalEntity` | `incorporationDate` | `dissolutionDate` |
| `File` | `date`, `authoredAt`, `publishedAt` | |
| `Contract` | `contractDate` | |
| `CourtCase` | `fileDate` | `closeDate` |
| … | … | … |

I’m not 100% sure about this yet (and whether this should be part of the FtM model), but wanted to bring this up for discussion early. Also we already do something similar with the `edge` metadata.

Related:
* https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/temporal
* https://schema.org/temporalCoverage

**Comment by pudo** [comment]
Proposed verbiage in the schema files:

```yaml
Test:
   extends: ....
   temporalExtent:
      start: 
        - startDate
        - date
      end:
         - endDate
         - date
```

**Comment by tillprochaska** [comment]
I have written this done in a slightly more detailed form. Would love to hear feedback/comments. Any edge cases that aren’t covered by this? Does the naming make sense?

***

Schema YAML files support an new, optional key `temporalExtent` to store metadata about the properties that should be considered the temporal start and end of an entity:

```yml
Event:
  ...
  temporalExtent:
    start:
      - startDate
      - date
    end:
      - endDate
      - date
  ...
```

`start` and `end` are lists of properties, as in some cases multiple properties can be used as the start or end date when displaying an entity in a timeline. For example, a multi-day event might have the `startDate` and `endDate` properties set, while a single-day event might only have the `date` property filled out.

`start` and `end` properties must be of type `Date`.

If multiple `start` properties of an entity are set or if properties have multiple values, the smallest value should be considered the temporal start.

If multiple `end` properties of an entity are set or if properties have multiple values, the largest value should be considered the temporal end.

In the following examples, `2022-01-01` should be considered the temporal start of the entites and `2022-03-01` should be considered the temporal end.

```json
{
  "schema": "Event",
  "startDate": ["2022-02-01", "2022-01-01"],
  "endDate": ["2022-03-01", "2022-02-01"]
}
```

```json
{
  "schema": "Event",
  "startDate": ["2022-01-01"],
  "date": ["2022-02-01"],
  "endDate": ["2022-03-01"]
}
```

## Helper methods

Entity proxy objects (in the Python and TS libraries) should provide new helper methods to retrieve the temporal start and end of an entity.

```ts
getTemporalStart(): Value { /* ... */ }
getTemporalEnd(): Value { /* ... */ }
```

```py
@property
def temporal_start() -> str:
  # ...

@property
def temporal_end() -> str:
  # ...
```

*Maybe these methods should return parsed date objects, (`date.date` in Python and `Date` instances in TS)?*

Schema objects should provide new helper methods to retrieve the start and end properties:

```ts
getTemporalStartProperties(): Array<Property> { /* ... */ }
getTemporalEndProperties(): Array<Property> { /* ... */ }
```

```py
@property
def temporal_start() -> str:
  # ...

@property
def temporal_end() -> str:
  # ...
```

## Inheritance

The temporal start and end properties should be inherited. In the following example, the temporal start properties of `Event` are `startDate` and `date`, because `Event` extends `Interval`.

```yml
Interval:
  ...
  temporalExtent:
    start:
      - startDate
      - date
    end:
      - endDate
      - date

Event:
  ...
  extends:
    - Interval
```

**Comment by pudo** [comment]
Complete +1 on this plan. Do you need help with the Python side of the implementation?

**Comment by tillprochaska** [comment]
@pudo Thanks! I implemented this as a prototype in both Python and TS to get a feeling for what the API could look like and was able to find my way around, but would probably need some feedback on the implementation. I can put in a PR and add PR comments to the relevant parts of the code?
