### ISSUE TITLE
Person entities have `incorporationDate`, `dissolutionDate`

### ISSUE THREAD

**Issue by tillprochaska** [alephdata/followthemoney#880]
The `Person` schema inherits `incorporationDate` and `dissolutionDate` properties from `LegalEntity`. I guess this isn’t really intended and rather a side-effect of the inheritance hierarchy?

Aleph’s new timelines UI will allow users to create entities of any schema to timelines. When adding a new entity to a timeline, the UI will display date inputs based on the temporal extent properties. In the case of the `Person` schema, these are:

* `incorporationDate`
* `dissolutionDate`
* `birthDate`
* `deathDate`

This is slightly confusing for end users, so basically I’m wondering how to solve this:

* Adjust the FtM model: Move `incorporationDate` + `dissolutionDate` to the `Organization` schema
* Hard code a special case in the UI and hide `incorporationDate`/`dissolutionDate` fields when adding entities to timelines.

**Comment by pudo** [comment]
I think incorp/dissolution date used to originally live on `Organization` and we moved it down in response to a few mappings where we had a lot of stuff where we didn't know if it was people or companies, and some of them had incorp dates. So OCCRP may have to re-work a few mappings to fix this. Also curious if there's a world where sole traders may fall into this (e.g. I am born 1985, incorporated 2021).

**Comment by tillprochaska** [comment]
@pudo, oh, that is very helpful background information, thanks! I’ll ask the data team about this, but I think in this case I’ll probably just hide those two inputs in the UI when creating a new timeline item.

**Comment by tillprochaska** [comment]
Got some additional feedback from Eric on this who also confirmed that changing mappings would be a significant effort (or not event possible because there’s no way to differentiate between org/person in some cases).

I’m going to hard code this special case in the UI to hide the two inputs, as I think in 99% of the use cases it will probably confuse users.

<img width="507" alt="Screen Shot 2022-11-10 at 13 17 31" src="https://user-images.githubusercontent.com/1512805/201090830-7a82dce2-c3a7-4a70-92de-0e352a28af8c.png">
