### ISSUE TITLE
Updated README to include release instructions

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/followthemoney#912]
What it says in the title. Update the README with instructions on how someone would go about doing a new FtM release.

**Comment by stchris** [comment]
@Rosencrantz is there something missing from https://github.com/alephdata/followthemoney#releasing ?

**Comment by Rosencrantz** [comment]
I mean, no, not really. As ever I only read the first sentence and didn't get the full picture.  I think that maybe we could provide a bit more context around things like needing a transifex token etc. but that isn't the end of the world.
