### ISSUE TITLE
Events involved doesn't accept 'entities' list, but only entity.

### ISSUE THREAD

**Issue by brrttwrks** [alephdata/followthemoney#923]
The event schema accepts an _involved_ property that should take one or more entities, but currently only takes one entity using _entity_. _entities_ doesn't fail, but doesn't create the desired output, which is to create multiple intervals. Instead it does nothing. The ideal behavior is that _involved_ takes either _entity_ for one or _entities_ and a list for  more than one entity.

**Comment by pudo** [comment]
I'm really confused: is this a UI problem in the timelines or somewhere? `involved` is multi-valued, of course, like everything else in the data model :)
