### ISSUE TITLE
`Passport` has two different passport number properties

### ISSUE THREAD

**Issue by tillprochaska** [alephdata/followthemoney#924]
Just noticed that the `Passport` schema has a `passportNumber` property, but it also inherits `Identification:number`. Both properties have the "Passport number" label.

Wondering if we could remove `Passport:passportNumber` (batched together with other breaking changes) or if there’s a specific reason for this?

<img width="774" alt="Screen Shot 2022-12-02 at 15 31 39" src="https://user-images.githubusercontent.com/1512805/205316074-5505770e-5238-4a02-b194-4e58774eb40d.png">

**Comment by pudo** [comment]
Removing it is a good idea, I think it was a consistency thing that went bad. We could mark it hidden now?

**Comment by tillprochaska** [comment]
> We could mark it hidden now?

I’d have to check Aleph’s implementation to see if we show hidden properties with a non-empty value. Pretty sure that both properties have been used so far, so we need to ensure we don’t hide data that’s already in Aleph.

**Comment by Legless** [comment]
Since `Identification` can used for a variety of documents (from docs - national ID cards, voter enrollments and similar instruments) - can we have it's `number` label renamed from `Passport number` to something more neutral please?

**Comment by tillprochaska** [comment]
Fixed in #959
