### ISSUE TITLE
Proposal for some schema changes

### ISSUE THREAD

**Issue by Legless** [alephdata/followthemoney#952]
Hey. 

I'm using FtM mapping in my project, and while developing data mappings got some ideas: 

1. Rename `Identification:number` label from `Passport number` to something less specific, since `Identification` can be used not only for passports, but for a variety of documents.

2. Add `ipAddress` property to `UserAccount`.
Currently IP used only in `Analyzable:ipMentioned`, but would be nice to have it attached to account entity. 

3. `Event` have `location` property, but since it extends `Thing` - it's already have `address` and `addressEntity`. 
Probably this should be removed/reworked?

**Comment by pudo** [comment]
Good suggestions! Re 1) -- maybe `document number`? Want to draft a PR? They're all relatively small changes so I imagine we could throw them together :)

**Comment by tillprochaska** [comment]
@Legless I’ve started a [list of small inconsistencies/issues](https://github.com/alephdata/followthemoney/discussions/948) which would require breaking changes in order to be resolved. I’ve added 3) to the list so we remember this when the next major version of FtM is released. :)

**Comment by Legless** [comment]
@tillprochaska nice, thank you.

**Comment by pudo** [comment]
Closing as there are no actions on this one left.
